services:
  mysql:
    build: .
    container_name: mysql-tuyensinh
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456a@"
    ports:
      - "3333:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    image: tomcat:9-jdk17
    container_name: servlet-backend
    depends_on:
      - mysql
    volumes:
      - ./backend-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    # ❌ KHÔNG expose port ra host → tránh CORS
    # ports: 
    #   - "8386:8080"

  frontend:
    image: nginx:alpine
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "18473:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
